### ISSUE TITLE
TypeScript対応

### ISSUE THREAD

**Issue by TinyKitten** [makotia/Matsuya-Web-API#60]
# TypeScript対応

* してもしなくてもいいと思うけど

**Comment by mak0tia** [comment]
TS理解してないんだけどNodeをTypeScriptでやるって認識でいいんだよね?

**Comment by TinyKitten** [comment]
せやな

**Comment by mak0tia** [comment]
全然理解してないから時間かかりそうだけどがんばる

**Comment by mak0tia** [comment]
暇な時にGoで書き換えるんだけどこれTSでもやった方がいいんか？？

**Comment by makotia** [comment]
closeしろって言ってんだろ
